export const TOP_GERMAN_GAMES = [
    "Die Siedler von Catan",
    "Carcassonne",
    "Zug um Zug",
    "Zug um Zug Europa",
    "Azul",
    "Dorfromantik: Das Brettspiel",
    "Cascadia",
    "Flügelschlag",
    "Die Crew: Reist gemeinsam zum 9. Planeten",
    "Just One",
    "Codenames",
    "Terraforming Mars",
    "Arche Nova",
    "Dune: Imperium",
    "Fantastische Reiche",
    "Die Quacksalber von Quedlinburg",
    "Sky Team",
    "Heat: Pedal to the Metal",
    "Challengers!",
    "MicroMacro: Crime City",
    "Paleo",
    "Die verlorenen Ruinen von Arnak",
    "Everdell",
    "Scythe",
    "7 Wonders",
    "7 Wonders Duel",
    "Dominion",
    "Pandemic",
    "Spirit Island",
    "Gloomhaven",
    "Die Legenden von Andor",
    "King of Tokyo",
    "Machi Koro",
    "Wizard",
    "6 nimmt!",
    "Heckmeck am Bratwurmeck",
    "Qwirkle",
    "Ubongo",
    "Dixit",
    "Concept",
    "Magic Maze",
    "Hanabi",
    "Love Letter",
    "Skull King",
    "The Mind",
    "Werwölfe von Düsterwald",
    "Risiko",
    "Monopoly",
    "Spiel des Lebens",
    "Scotland Yard"
];
